version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk  # Updated Java version

    working_directory: ~/project

    steps:
      - checkout

      # Restore cached Maven dependencies (if any)
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Setup Environment
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build and Test
          command: mvn clean package  # Adjusted Maven command

      # Store Maven dependencies in cache
      - save_cache:
          paths:
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
