version: 2.1

jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk17

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Setup Environment
          command: |
            echo 'export JAVA_HOME=/opt/java/openjdk' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build and Test
          command: mvn clean install -DskipTests=false

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
