version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-22  # Use a Docker image with Maven 3.8.4 and Java 22

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn clean install -DskipTests=false

      - save_cache:
          paths:
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
