version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk

    working_directory: ~/app

    steps:
      - checkout

      # Restore cached Maven dependencies (if any)
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Setup Environment
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build and Test
          command: mvn clean install -DskipTests=false

      # Store Maven dependencies in cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
